# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VRPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vrpage_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('email_username', models.CharField(max_length=255)),
                ('email_password', models.CharField(max_length=50)),
                ('email_server', models.CharField(max_length=50)),
                ('email_from_name', models.CharField(max_length=50)),
            ],
        ),
    ]
