# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolishedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polished_url', models.URLField()),
                ('polished_email', models.EmailField(max_length=254)),
                ('page_title', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=30)),
                ('anchor_text', models.CharField(max_length=255)),
                ('first_message_sent', models.BooleanField(default=False)),
                ('second_message_sent', models.BooleanField(default=False)),
                ('unsubscribe_permanently', models.BooleanField(default=False)),
                ('unsubscribe_from_vrpage', models.BooleanField(default=False)),
                ('vrpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrpages.VRPage')),
            ],
        ),
    ]
