# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0002_polishedurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_type', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('message_body', models.TextField()),
                ('vrpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrpages.VRPage')),
            ],
        ),
    ]
