# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0004_emailmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscribed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('permanent', models.BooleanField(default=False)),
                ('domain', models.CharField(blank=True, max_length=50)),
                ('entire_domain', models.BooleanField(default=False)),
                ('vrpage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vrpages.VRPage')),
            ],
        ),
    ]
