# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrpages', '0005_unsubscribed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unsubscribed',
            options={'verbose_name_plural': 'unsubscribes'},
        ),
        migrations.AlterField(
            model_name='unsubscribed',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
